# Generated by Django 4.2.1 on 2023-07-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=200)),
                ('año', models.IntegerField()),
                ('kilometraje', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('vehiculo', models.CharField(max_length=300)),
                ('es_nuevo', models.BooleanField()),
            ],
        ),
    ]
